### FastText

##### Basic information
   - developed by Facebook AI Research (FAIR) lab
   - uses C++11 & Python (python is the officially supported language)
   - packages: fasttext, gensim.models.FastText
    
    
### Word Representation (unsupervised)

   - Basic model comprises of negative log-likelihood 
       > $$ log (1 + e ^ {-s(w_{t},w_{c})}) + \sum_{n \in \mathcal{N}_{t,c}} log( 1 +  e ^ {-s(w_{t},n)})$$ 
       > where $s(w_{t},w_{c})$ maps words the context vectors to a score and is given by the dot product $s(w_{t},w_{c}) = \mathbf{u}_{w_{t}}^{T} \cdot \mathbf{v}_{w_{c}}$ , and $\mathcal{N}_{t,c}$ is a set of negative samples \
       > with 
       > $cos(\theta) = \frac{\mathbf{A} \cdot \mathbf{B}} {\lVert \mathbf{A} \rVert \cdot \lVert \mathbf{B} \rVert} $ , $\theta \propto$ objective function
   
   - Hence, the objective function is
   
        > $$ \sum_{t = 1}^{T} \left[{ \sum_{c \in \mathcal{C}_{t} } \mathit{l} (s(w_{t}, w_{c})) + \sum_{n \in \mathcal{N}_{t,c}} \mathit{l} (-s(w_{t}, n)) } \right]   $$
        > where $l : x \mapsto \log (1+e^{-x}) $
   
   - Character n-grams _ each word is represented by the sum of the vector representations of its n-grams, obtaining the resulting scoring function
       > $$ s(w,c) = \sum_{g \in \mathcal{g}_{w}} \mathbf{z}_{g}^{T} \cdot \mathbf{v}_{c} $$
       > where given a dictionary of n-grams of size $G$, $\mathcal{g}_{w} \subset \{1, ... , G\}$ denotes the set of n-grams appearing in a word $w$
       
   
    
    
### Text classification (supervised)
   - Classify texts on 

> Understanding the relationship between the predictors $X$ and the response $Y$ \
        > eg. Which predictor among $X_1, X_2, ..., X_p$ has the greatest impact on the value of the response $Y$?\
        > eg. What is the relationship between the response and each predictor?

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import fasttext
from gensim.models import Word2Vec, FastText


# for specific usage of packages, refer to the links below

# FastText
# https://fasttext.cc/docs/en/supervised-tutorial.html
# https://fasttext.cc/docs/en/unsupervised-tutorial.html
# https://fasttext.cc/docs/en/cheatsheet.html

# gensim 
# https://radimrehurek.com/gensim/models/fasttext.html

In [13]:
direc = "/home/eppen/Documents/YBIGTA/WinterSchool/NLP/tokenized/"

mecab_direc = direc + "ratings_mecab.txt"

corpus = [sent.strip().split(" ") for sent in open(mecab_direc).readlines()]

In [2]:
# Text Classification

model_without_char = fasttext.train_supervised(input="/home/eppen/fastText/cooking.train", lr=0.5, epoch=25, wordNgrams=2, dim=50, loss='hs', maxn=0)
model_with_char = fasttext.train_supervised(input="/home/eppen/fastText/cooking.train", lr=0.5, epoch=25, wordNgrams=2, dim=50, loss='hs', minn = 2, maxn = 5)

In [10]:
print("creat" in model_without_char.words)

model_without_char.get_nearest_neighbors("creat")

False


[(0.0, 'the'),
 (0.0, 'to'),
 (0.0, 'How'),
 (0.0, 'of'),
 (0.0, 'I'),
 (0.0, 'for'),
 (0.0, 'What'),
 (0.0, 'explosive?'),
 (0.0, 'savory?'),
 (0.0, 'formal')]

In [11]:
print("creat" in model_with_char.words)

model_with_char.get_nearest_neighbors("creat")

False


[(0.8133785724639893, 'creates'),
 (0.811210036277771, 'create'),
 (0.8019700646400452, 'creating'),
 (0.7804949879646301, 'cream,'),
 (0.7777360677719116, 'cream"?'),
 (0.7776616215705872, 'cream"'),
 (0.7684035301208496, 'cream.'),
 (0.765713632106781, 'creamer-'),
 (0.7637524008750916, 'creamy?'),
 (0.7592759728431702, 'creams')]

In [20]:
model_without_char.predict("Howe creatss chokolate berger?")

(('__label__spicy-hot',), array([0.07255475]))

In [21]:
model_with_char.predict("Howe creatss chokolate berger?")

(('__label__chocolate',), array([0.15656056]))

In [14]:
### traditional word2vec

w2v_model = Word2Vec(corpus, size=100, workers=4, window = 5, sg = 1)

In [15]:
w2v_model.wv.vocab

{'어릴': <gensim.models.keyedvectors.Vocab at 0x7fa9137ef710>,
 '때': <gensim.models.keyedvectors.Vocab at 0x7fa9137ef890>,
 '보': <gensim.models.keyedvectors.Vocab at 0x7fa9137ef690>,
 '고': <gensim.models.keyedvectors.Vocab at 0x7fa9137efcd0>,
 '지금': <gensim.models.keyedvectors.Vocab at 0x7fa9137ef8d0>,
 '다시': <gensim.models.keyedvectors.Vocab at 0x7fa913415750>,
 '봐도': <gensim.models.keyedvectors.Vocab at 0x7fa934ba0d10>,
 '재밌': <gensim.models.keyedvectors.Vocab at 0x7fa934ba04d0>,
 '어요': <gensim.models.keyedvectors.Vocab at 0x7fa9137ef950>,
 'ㅋㅋ': <gensim.models.keyedvectors.Vocab at 0x7fa964e838d0>,
 '디자인': <gensim.models.keyedvectors.Vocab at 0x7fa934ba0e10>,
 '을': <gensim.models.keyedvectors.Vocab at 0x7fa934ba0c50>,
 '배우': <gensim.models.keyedvectors.Vocab at 0x7fa934ba0f90>,
 '는': <gensim.models.keyedvectors.Vocab at 0x7fa934ba0f50>,
 '학생': <gensim.models.keyedvectors.Vocab at 0x7fa934ba0c10>,
 '으로': <gensim.models.keyedvectors.Vocab at 0x7fa934ba0e90>,
 ',': <gensim.models.keyedve

In [24]:
w2v_model.wv["학생"]

array([-1.22366361e-01, -4.22951996e-01, -1.40534148e-01, -1.39218107e-01,
        2.01533690e-01, -2.37655371e-01, -3.14339072e-01,  6.18804753e-01,
       -4.26740795e-01, -1.61584556e-01,  2.16992825e-01, -2.48778254e-01,
        7.58886337e-02,  1.09758355e-01, -1.91073984e-01,  1.19586669e-01,
       -2.37545922e-01, -2.36076251e-01, -6.29425824e-01,  9.77123454e-02,
        4.52619903e-02, -3.00871015e-01, -4.42951262e-01,  7.29622468e-02,
       -4.81326461e-01,  1.85424581e-01, -4.01591271e-01, -1.20665580e-01,
        2.93009222e-01, -2.59617895e-01,  1.89215943e-01, -2.64486462e-01,
       -2.76598930e-01,  4.23589617e-01, -9.42701623e-02, -3.68814260e-01,
        5.38994968e-02,  8.37390199e-02, -1.83879901e-02, -3.19145441e-01,
       -1.07608646e-01, -4.35492843e-01,  2.39408150e-01,  1.99872062e-01,
       -2.59281784e-01,  1.55252188e-01,  2.42085814e-01, -3.84904966e-02,
       -7.14441717e-01, -9.62827280e-02,  5.97994030e-01,  3.54680568e-01,
        1.89730749e-01, -

In [16]:
w2v_model.wv.most_similar("학생")

[('초등학생', 0.7300482988357544),
 ('고등학생', 0.7249009013175964),
 ('연령', 0.7200811505317688),
 ('자녀', 0.7080414295196533),
 ('저학년', 0.7011663913726807),
 ('대학', 0.7011204957962036),
 ('중학생', 0.6970521807670593),
 ('대학생', 0.6850579977035522),
 ('학년', 0.6804635524749756),
 ('졸업', 0.6788170337677002)]

In [26]:
# default: 100 dimensions
# default: 3-6 characters
# default: 1~5 windows

In [27]:
# Trained with fasttext

# fasttext.train_unsupervised(corpus)  --> 컴퓨터 사망

In [18]:
# Trained with gensim

model_gs = FastText()

model_gs.build_vocab(sentences = corpus)
model_gs.train(sentences = corpus, total_examples = len(corpus), epochs=10)

In [19]:
model_gs.wv.vocab

{'어릴': <gensim.models.keyedvectors.Vocab at 0x7fa912a1d8d0>,
 '때': <gensim.models.keyedvectors.Vocab at 0x7fa912a1d4d0>,
 '보': <gensim.models.keyedvectors.Vocab at 0x7fa912a1ded0>,
 '고': <gensim.models.keyedvectors.Vocab at 0x7fa912a1ddd0>,
 '지금': <gensim.models.keyedvectors.Vocab at 0x7fa912fba210>,
 '다시': <gensim.models.keyedvectors.Vocab at 0x7fa912fba290>,
 '봐도': <gensim.models.keyedvectors.Vocab at 0x7fa912fba2d0>,
 '재밌': <gensim.models.keyedvectors.Vocab at 0x7fa912fba310>,
 '어요': <gensim.models.keyedvectors.Vocab at 0x7fa912fba110>,
 'ㅋㅋ': <gensim.models.keyedvectors.Vocab at 0x7fa912fba250>,
 '디자인': <gensim.models.keyedvectors.Vocab at 0x7fa912fba350>,
 '을': <gensim.models.keyedvectors.Vocab at 0x7fa912fba390>,
 '배우': <gensim.models.keyedvectors.Vocab at 0x7fa912fba3d0>,
 '는': <gensim.models.keyedvectors.Vocab at 0x7fa912fba410>,
 '학생': <gensim.models.keyedvectors.Vocab at 0x7fa912fba450>,
 '으로': <gensim.models.keyedvectors.Vocab at 0x7fa912fba490>,
 ',': <gensim.models.keyedve

In [20]:
model_gs.wv["학생"]

array([ 0.635347  , -1.1881287 , -0.05690816, -0.5034903 , -0.25509194,
       -0.66835785, -1.3173845 ,  2.0753272 ,  0.2773064 ,  0.02746377,
        0.8725078 , -0.16413465,  1.2955999 , -0.02551849,  1.7178278 ,
        0.39547753,  0.5844992 ,  1.2765881 , -1.2318469 ,  0.53805125,
       -2.3744287 , -0.55451065,  0.6312205 ,  0.8019048 ,  0.19108143,
       -1.9580715 , -0.37050813, -0.45851806,  1.1884024 , -0.5362304 ,
        0.48284498,  0.0677035 , -1.4432548 ,  0.5656309 ,  0.5864675 ,
        0.06080135, -0.11124946, -0.55711484, -0.75315654,  0.09372663,
       -0.7930292 ,  1.0486289 , -0.9556998 , -2.006343  ,  1.8683054 ,
        1.6715971 ,  1.9027728 ,  1.3078643 , -0.19267762,  0.59816307,
        0.624264  ,  0.27235633,  0.41193563, -0.0427651 ,  0.4812967 ,
       -0.667177  ,  0.9353783 ,  0.12240572, -0.55904865, -0.36227235,
        1.6308912 , -0.17515677,  1.0871775 , -1.246553  ,  0.35901743,
        0.09152261, -0.05789214,  1.3259295 ,  0.19243458, -1.10

In [22]:
model_gs.wv.most_similar("학생")

[('여학생', 0.893774151802063),
 ('국민학생', 0.8423455953598022),
 ('대학생', 0.8245558738708496),
 ('고등학생', 0.7951676845550537),
 ('초등학생', 0.7427849769592285),
 ('중학생', 0.7123082876205444),
 ('어린놈', 0.6801207065582275),
 ('군인', 0.6655428409576416),
 ('어린애', 0.6551915407180786),
 ('일반인', 0.6414783000946045)]

In [32]:
# Trained on bash, imported with fasttext

model = fasttext.load_model('/home/eppen/fastText/model.bin')

model.words
model.get_word_vector

<bound method _FastText.get_word_vector of <fasttext.FastText._FastText object at 0x7fd931124110>>

In [33]:
model.words

['.',
 '</s>',
 '이',
 '는',
 '영화',
 '다',
 '고',
 '하',
 '도',
 '의',
 '가',
 '은',
 '에',
 '을',
 '보',
 '한',
 '..',
 '게',
 ',',
 '들',
 '!',
 '지',
 '를',
 '있',
 '없',
 '?',
 '좋',
 '나',
 '1',
 '었',
 '만',
 '는데',
 '너무',
 '0',
 '봤',
 '안',
 '적',
 '정말',
 '로',
 '음',
 '것',
 '으로',
 '아',
 '재밌',
 '네요',
 '어',
 '점',
 '같',
 '진짜',
 '지만',
 '했',
 '에서',
 '기',
 '네',
 '않',
 '거',
 '았',
 '수',
 '되',
 '면',
 'ㅋㅋ',
 '과',
 '말',
 '연기',
 '인',
 '잘',
 '주',
 '최고',
 '평점',
 '내',
 '~',
 '이런',
 '던',
 '어요',
 '와',
 '2',
 '왜',
 '할',
 '해',
 '겠',
 '습니다',
 'ㅋㅋㅋ',
 '스토리',
 '...',
 '아니',
 '생각',
 '더',
 '드라마',
 '그',
 '싶',
 '사람',
 '듯',
 '때',
 '감동',
 '함',
 '배우',
 '까지',
 '본',
 '좀',
 '볼',
 '내용',
 '보다',
 '뭐',
 '만들',
 '알',
 '감독',
 '라',
 '재미',
 '그냥',
 '중',
 '지루',
 '시간',
 '재미있',
 '3',
 '년',
 '잼',
 '였',
 '재미없',
 '사랑',
 '냐',
 '못',
 '쓰레기',
 '서',
 '라고',
 '번',
 '야',
 '면서',
 '다시',
 '니',
 '나오',
 '작품',
 '이거',
 '하나',
 '해서',
 '줄',
 '개',
 '끝',
 '남',
 '정도',
 '이건',
 '마지막',
 '임',
 '액션',
 '기대',
 'ㅋ',
 '분',
 '라는',
 '입니다',
 '다는',
 '건',
 '완전',
 '많',
 '참',
 '아깝',
 '처음'

In [34]:
model.get_word_vector("학생")

array([ 1.43882930e-02, -1.41155377e-01, -2.22145274e-01, -2.94394225e-01,
        2.20219165e-01,  1.47111475e-01,  7.76096508e-02,  8.75757486e-02,
        2.80630231e-01, -1.26182348e-01, -5.33749819e-01, -4.04617861e-02,
       -1.54051334e-01, -4.99048054e-01,  2.03076228e-01, -2.40003280e-02,
        8.25563550e-01, -1.77272752e-01, -1.55364469e-01,  1.07840836e-01,
        8.83810580e-01,  1.52548239e-01, -7.46772066e-02,  1.49235606e-01,
       -1.40668839e-01, -1.30642340e-01, -5.28521776e-01,  2.88921118e-01,
       -3.56071323e-01, -1.44427627e-01,  8.59987140e-02, -1.76830843e-01,
        2.00584650e-01, -3.76861133e-02, -2.57336259e-01, -1.99530393e-01,
        9.41755623e-02, -6.73193038e-02, -1.60313696e-01, -4.06207293e-02,
       -5.44040263e-01,  1.28239319e-02,  1.13327794e-01, -7.95557499e-02,
       -3.03320915e-01, -1.17209360e-01,  6.57771587e-01,  7.07331449e-02,
        7.47766018e-01, -1.77244574e-01, -4.67090487e-01, -2.22572953e-01,
       -7.54924774e-01,  

In [35]:
model.get_nearest_neighbors("학생")

[(0.7290460467338562, '고등학생'),
 (0.728935956954956, '대학생'),
 (0.7154802083969116, '대학교'),
 (0.6990119218826294, '대학'),
 (0.6916933655738831, '졸업'),
 (0.6820202469825745, '학부모'),
 (0.6735225319862366, '고등'),
 (0.6733785271644592, '여학생'),
 (0.6693524122238159, '국민학생'),
 (0.6642491817474365, '다닐')]

In [36]:
# Trained on bash, imported with gensim

# Getting fasttext models in vec/bin format

# type the command below on bash
#./fasttext skipgram -input ratings_mecab.txt -output model

from gensim.models.wrappers import FastText

ft_model = FastText.load_fasttext_format('/home/eppen/fastText/model.bin')

In [37]:
ft_model.wv.vocab

{'.': <gensim.models.deprecated.keyedvectors.Vocab at 0x7fd93113f650>,
 '</s>': <gensim.models.deprecated.keyedvectors.Vocab at 0x7fd93113f750>,
 '이': <gensim.models.deprecated.keyedvectors.Vocab at 0x7fd93113f7d0>,
 '는': <gensim.models.deprecated.keyedvectors.Vocab at 0x7fd93113f850>,
 '영화': <gensim.models.deprecated.keyedvectors.Vocab at 0x7fd93113f8d0>,
 '다': <gensim.models.deprecated.keyedvectors.Vocab at 0x7fd93113f9d0>,
 '고': <gensim.models.deprecated.keyedvectors.Vocab at 0x7fd93113fa50>,
 '하': <gensim.models.deprecated.keyedvectors.Vocab at 0x7fd93113fad0>,
 '도': <gensim.models.deprecated.keyedvectors.Vocab at 0x7fd93113fb50>,
 '의': <gensim.models.deprecated.keyedvectors.Vocab at 0x7fd93113f950>,
 '가': <gensim.models.deprecated.keyedvectors.Vocab at 0x7fd93113fbd0>,
 '은': <gensim.models.deprecated.keyedvectors.Vocab at 0x7fd93113fc50>,
 '에': <gensim.models.deprecated.keyedvectors.Vocab at 0x7fd93113fcd0>,
 '을': <gensim.models.deprecated.keyedvectors.Vocab at 0x7fd93113fd50>,
 '

In [38]:
ft_model["학생"]

array([-0.0330895 , -0.0270534 ,  0.00037072, -0.09784418, -0.00952482,
        0.00571445, -0.00171212,  0.05215607,  0.06713373, -0.00252355,
       -0.09293189, -0.01954213, -0.05718217, -0.09266279, -0.00115381,
        0.01568371,  0.10514381,  0.00435491, -0.04847056,  0.07961261,
        0.19566284, -0.00381837,  0.02261642, -0.03712045, -0.07944328,
       -0.02372825, -0.06165854,  0.06187534, -0.08997138, -0.05017286,
       -0.05437044, -0.0565555 ,  0.04570846, -0.02776191, -0.00513409,
        0.00552711,  0.04365916, -0.08508383, -0.01864137,  0.00766175,
       -0.12852769, -0.02061407,  0.04464441, -0.08951019, -0.0909242 ,
       -0.02846727,  0.01021706, -0.05265512,  0.1163597 , -0.04003516,
       -0.0213875 , -0.01149839, -0.08584761,  0.0685202 , -0.00140243,
       -0.04016709, -0.0203314 ,  0.12113051,  0.0255988 , -0.004652  ,
        0.03553133,  0.06672967,  0.03015299,  0.04488355, -0.06597161,
        0.01558247,  0.01330374,  0.01990565, -0.13588716, -0.07

In [39]:
ft_model.wv.most_similar("학생")

[('가해자', 0.5095288157463074),
 ('자녀', 0.4758945405483246),
 ('학부모', 0.4737958014011383),
 ('개신교', 0.4690389931201935),
 ('선생', 0.4661126136779785),
 ('반정부', 0.4637138545513153),
 ('배부른', 0.4583195745944977),
 ('욕구', 0.4576117992401123),
 ('주민', 0.45282793045043945),
 ('옥한흠', 0.44178345799446106)]

In [13]:
temp_model_gs = FastText.load_fasttext_format('/home/eppen/fastText/jamo_model.bin')

/home/eppen/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `load_fasttext_format` (use load_facebook_vectors (to use pretrained embeddings) or load_facebook_model (to continue training with the loaded full model, more RAM) instead).
  """Entry point for launching an IPython kernel.


In [12]:
temp_model_ft = fasttext.load_model('/home/eppen/fastText/jamo_model.bin')

In [14]:
# from https://github.com/ratsgo/embedding

from soynlp.hangle import decompose, compose, character_is_korean
import re

doublespace_pattern = re.compile('\s+')

def jamo_sentence(sent):

    def transform(char):
        if char == ' ':
            return char
        cjj = decompose(char)
        if len(cjj) == 1:
            return cjj
        cjj_ = ''.join(c if c != ' ' else '-' for c in cjj)
        return cjj_

    sent_ = []
    for char in sent:
        if character_is_korean(char):
            sent_.append(transform(char))
        else:
            sent_.append(char)
    sent_ = doublespace_pattern.sub(' ', ''.join(sent_))
    return sent_


def jamo_to_word(jamo):
    jamo_list, idx = [], 0
    while idx < len(jamo):
        if not character_is_korean(jamo[idx]):
            jamo_list.append(jamo[idx])
            idx += 1
        else:
            jamo_list.append(jamo[idx:idx + 3])
            idx += 3
    word = ""
    for jamo_char in jamo_list:
        if len(jamo_char) == 1:
            word += jamo_char
        elif jamo_char[2] == "-":
            word += compose(jamo_char[0], jamo_char[1], " ")
        else:
            word += compose(jamo_char[0], jamo_char[1], jamo_char[2])
    return word

In [3]:
jamo_sentence("서울특별시")

'ㅅㅓ-ㅇㅜㄹㅌㅡㄱㅂㅕㄹㅅㅣ-'

In [1]:
for i in temp_model_gs.wv.most_similar(jamo_sentence("서울특벌시")):
    print(jamo_to_word(i[0]), i[1])

NameError: name 'temp_model_gs' is not defined

In [72]:
# ./fasttext skipgram -input /home/eppen/Documents/YBIGTA/WinterSchool/NLP/tokenized/corpus_mecab_jamo.txt -output jamo_model_nlp

In [2]:
###################################################################

In [ ]:
# loading pre-trained data (doesnt work on jupyter)
from gensim.models import fasttext
#note the difference from gensim.models.FastText and gensim.models.wrappers.fasttext
model_pt_gs = fasttext.load_facebook_vectors("/home/eppen/Downloads/cc.ko.300.bin")

In [ ]:
model_pt_gs.wv.vocab